runner:
  govet:
    cmd: go vet -all #$(go list ./pkg/...)
    format: govet
    level: warning
  gosec:
    cmd: gosec -quiet -no-fail -fmt golint ./pkg/...
    format: golint
    level: warning
  staticcheck:
    cmd: staticcheck -fail none $(go list ./pkg/...)
    errorformat:
      - "%f:%l:%c: %m"