name: Application Validation

on:
  pull_request:

jobs:
  build_change:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Change
        uses: actions/checkout@v3
        with:
          path: change
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/MANIFEST.MF') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build Change
        working-directory: ./change
        run: >
          ./mvnw -B -U package -Dmaven.test.skip=true
          -Dstyle.color=always
          -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
          -Dorg.slf4j.simpleLogger.log.org.eclipse.tycho.core.resolver.DefaultTychoResolver=warn
          -Dorg.slf4j.simpleLogger.log.org.eclipse.tycho.osgi.configuration.MavenContextConfigurator=warn
          -Dorg.slf4j.simpleLogger.log.org.eclipse.sisu.equinox.launching.internal.DefaultEquinoxLauncher=warn
          -Dorg.slf4j.simpleLogger.log.org.eclipse.xtext.maven.XtextGenerateMojo=warn
          -Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.NoOpLog
        env: 
          MAVEN_OPTS: -Djansi.force=true
      - name: Store Change Artifact
        uses: actions/upload-artifact@v3
        with:
          name: change
          path: change/releng/tools.vitruv.change.updatesite/target/repository
          retention-days: 1
validate_applications:
  needs: build_change
  runs-on: ubuntu-latest
  steps:
    - name: Download Change Artifact
      uses: actions/download-artifact@v3
      with:
        name: change
        path: change
    - name: Checkout Framework
      uses: actions/checkout@v3
      with:
        path: framework
        repository: vitruv-tools/Vitruv
        ref: main
        fetch-depth: 0
    - name: Checkout DSLs
      uses: actions/checkout@v3
      with:
        path: dsls
        repository: vitruv-tools/Vitruv-DSLs
        ref: main
        fetch-depth: 0
    - name: Checkout CBS Applications
      uses: actions/checkout@v3
      with:
        path: cbsapplications
        repository: vitruv-tools/Vitruv-Applications-ComponentBasedSystems
        ref: main
        fetch-depth: 0
    - name: Checkout Matching Framework/DSLs/Applications Branches
      run: |
        cd framework
        git checkout -B ${{ github.head_ref }} origin/${{ github.head_ref }} || true
        cd ../dsls
        git checkout -B ${{ github.head_ref }} origin/${{ github.head_ref }} || true
        cd ../cbsapplications
        git checkout -B ${{ github.head_ref }} origin/${{ github.head_ref }} || true
    - name: Cache
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/MANIFEST.MF') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 11
    - name: Build Framework
      working-directory: ./framework
      run: >
        ./mvnw -B -U clean verify
        -Dvitruv.change.url="file:///\${GITHUB_WORKSPACE}/change"
        -Dstyle.color=always
        -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        -Dorg.slf4j.simpleLogger.log.org.eclipse.tycho.core.resolver.DefaultTychoResolver=warn
        -Dorg.slf4j.simpleLogger.log.org.eclipse.tycho.osgi.configuration.MavenContextConfigurator=warn
        -Dorg.slf4j.simpleLogger.log.org.eclipse.sisu.equinox.launching.internal.DefaultEquinoxLauncher=warn
        -Dorg.slf4j.simpleLogger.log.org.eclipse.xtext.maven.XtextGenerateMojo=warn
        -Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.NoOpLog
      env: 
        MAVEN_OPTS: -Djansi.force=true
    - name: Build DSLs
      uses: GabrielBB/xvfb-action@v1
      with:
        working-directory: ./dsls
        run: >
          ./mvnw -B -U clean verify
          -Dvitruv.change.url=file:///${GITHUB_WORKSPACE}/change
          -Dvitruv.framework.path=${GITHUB_WORKSPACE}/framework
          -Dstyle.color=always
          -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
          -Dorg.slf4j.simpleLogger.log.org.eclipse.tycho.core.resolver.DefaultTychoResolver=warn
          -Dorg.slf4j.simpleLogger.log.org.eclipse.tycho.osgi.configuration.MavenContextConfigurator=warn
          -Dorg.slf4j.simpleLogger.log.org.eclipse.sisu.equinox.launching.internal.DefaultEquinoxLauncher=warn
          -Dorg.slf4j.simpleLogger.log.org.eclipse.xtext.maven.XtextGenerateMojo=warn
          -Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.NoOpLog
      env: 
        MAVEN_OPTS: -Djansi.force=true
    - name: Build Applications
      uses: GabrielBB/xvfb-action@v1
      with:
        working-directory: ./cbsapplications
        run: >
          ./mvnw -B -U clean verify
          -Dvitruv.change.url=file:///${GITHUB_WORKSPACE}/change
          -Dvitruv.framework.path=${GITHUB_WORKSPACE}/framework
          -Dvitruv.dsls.path=${GITHUB_WORKSPACE}/dsls
          -Dstyle.color=always
          -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
          -Dorg.slf4j.simpleLogger.log.org.eclipse.tycho.core.resolver.DefaultTychoResolver=warn
          -Dorg.slf4j.simpleLogger.log.org.eclipse.tycho.osgi.configuration.MavenContextConfigurator=warn
          -Dorg.slf4j.simpleLogger.log.org.eclipse.sisu.equinox.launching.internal.DefaultEquinoxLauncher=warn
          -Dorg.slf4j.simpleLogger.log.org.eclipse.xtext.maven.XtextGenerateMojo=warn
          -Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.NoOpLog
      env: 
        MAVEN_OPTS: -Djansi.force=true
