name: Checkstyle

# workflow triggers
on:
  # manually
  workflow_dispatch:
  workflow_call:
  # PRs on `main`
  pull_request:
    branches:
    - build/pure-maven

jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
    

