name: CI

on:
  push:
    branches: [main]
  release:
    types: [created]
  pull_request:
  schedule:
    - cron: '0 2 30 * *' # run nightly at 2:30 am

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/MANIFEST.MF') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build and Verify
        run: >
          ./mvnw -B -U clean verify 
          -Dstyle.color=always
          -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
          -Dorg.slf4j.simpleLogger.log.org.eclipse.tycho.core.resolver.DefaultTychoResolver=warn
          -Dorg.slf4j.simpleLogger.log.org.eclipse.tycho.osgi.configuration.MavenContextConfigurator=warn
          -Dorg.slf4j.simpleLogger.log.org.eclipse.sisu.equinox.launching.internal.DefaultEquinoxLauncher=warn
          -Dorg.slf4j.simpleLogger.log.org.eclipse.xtext.maven.XtextGenerateMojo=warn
          -Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.NoOpLog
        env: 
          MAVEN_OPTS: -Djansi.force=true
      - name: Publish Nightly Update Site
        if: github.ref == 'refs/heads/main' && github.repository_owner == 'vitruv-tools'
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.UPDATE_SITE_DEPLOY_KEY }}
          external_repository: vitruv-tools/updatesite
          destination_dir: nightly/change
          publish_dir: releng/tools.vitruv.change.updatesite/target/repository
          publish_branch: main
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
      - name: Determine Release Version
        if: github.event_name == 'release' && github.repository_owner == 'vitruv-tools'
        id: releaseVersion
        run: |
          releaseVersion=$(echo ${{ github.event.release.tag_name }} | sed 's/^Releases\///') #trimm "Releases/" prefix from tag name
          echo "::set-output name=tag::$releaseVersion"
      - name: Publish Release Update Site
        if: github.event_name == 'release' && github.repository_owner == 'vitruv-tools'
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.UPDATE_SITE_DEPLOY_KEY }}
          external_repository: vitruv-tools/updatesite
          destination_dir: release/change/${{ steps.releaseVersion.outputs.tag }}
          publish_dir: releng/tools.vitruv.changeupdatesite/target/repository
          publish_branch: main
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
