name: Continuous Integration Workflow

# workflow triggers
on:
  # manually
  workflow_dispatch:
  # PRs on `main`
  #pull_request:
  #  branches:
  #  - main
  # nightly
  #schedule:
  #- cron: "0 3 * * *"

jobs:
  # main job for PRs/nightly on different operating systems
  ci:
    name: CI on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
    # checkout repository
    - name: Checkout
      uses: actions/checkout@v4.1.1

    # setup Java and cache Maven dependencies
    - name: Setup Java
      uses: actions/setup-java@v3.13.0
      with:
        distribution: 'temurin'
        java-version: '17'
        check-latest: true
        cache: 'maven'

    # run Maven build
    - name: Maven Build
      run: ./mvnw --batch-mode --update-snapshots verify

    # copy build results to staging area
    - name: Stage Build Results
      run: mkdir staging-${{ matrix.os }} && cp **/target/*.jar staging-${{ matrix.os }}/

    # upload staged packages
    - name: Upload Build Results
      uses: actions/upload-artifact@v3.1.3
      with:
        name: Build Results
        path: staging-*/
