name: Test Build

# workflow triggers
on:
  # manually
  workflow_dispatch:
  workflow_call:
  # PRs on `main`
  pull_request:
    #branches:
    #- main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      actions: write
      checks: write
      id-token: write
      #deployments: read|write
      issues: write
      packages: read
      #packages: write
      #repository-projects: read|write
      #security-events: read|write
      statuses: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        
      # setup Java and cache Maven dependencies
      - name: Setup Java
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true
          cache: 'maven'

      # run Maven build
      - name: Maven Build
        run: ./mvn --batch-mode --update-snapshots verify
        #run: ./mvnw --batch-mode --update-snapshots clean org.jacoco:jacoco-maven-plugin:0.8.8:prepare-agent verify org.jacoco:jacoco-maven-plugin:0.8.9:report-aggregate
      