name: Push on main checks

# workflow triggers
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - build/pure-maven

jobs:
  action-checkout:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  sonarqube:
    permissions: read-all
    needs: action-checkout
    uses: ./.github/workflows/sonarqube.yml

          
