name: Push on main checks

# workflow triggers
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - build/pure-maven

jobs:
  action-checkout:
    name: Checkout Actions
    runs-on: ubuntu-latest
    outputs:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_PROJECT_STATUS_API_URL: ${{ secrets.SONAR_PROJECT_STATUS_API_URL }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
  sonarqube:
    permissions: read-all
    needs: action-checkout
    uses: ./.github/workflows/sonarqube.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_PROJECT_STATUS_API_URL: ${{ secrets.SONAR_PROJECT_STATUS_API_URL }}

          
