name: Jacoco

# workflow triggers
on:
  # manually
  workflow_dispatch:
  workflow_call:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
        - uses: actions/checkout@v1
        - name: Checkstyle
          uses: ./.github/workflows/checkstyle
        - name: Jacoco
          uses: ./.github/workflows/jacoco