name: Jacoco

# workflow triggers
on:
  workflow_dispatch:
  workflow_call:
  pull_request:

jobs:
  checkstyle:
    uses: ./.github/workflows/checkstyle.yml
  jacoco:
    uses: ./.github/workflows/jacoco.yml
          
