name: Continuous Integration Workflow

# workflow triggers
on:
  workflow_dispatch:
  #push:
    #branches:
      #- build/pure-maven

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run SonarQube container
      run: docker run -d --name sonarqube -e SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true -p 9000:9000 sonarqube:latest
    
    - name: Setup Java
      uses: actions/setup-java@v3.13.0
      with:
        distribution: 'temurin'
        java-version: '17'
        check-latest: true
        cache: 'maven'

    - name: SonarQube Scan
      run: |
        mvn clean verify sonar:sonar \ 
          -Dsonar.projectKey=localVitruv \ 
          -Dsonar.projectName='localVitruv' \ 
          -Dsonar.host.url=http://localhost:9000 \ 
          -Dsonar.token=sqp_72900e6256c76923bb0920ebd6a2c6ab52fc0d3d

    - name: Stop and remove SonarQube container
      run: docker stop sonarqube && docker rm sonarqube