name: Static Code Review

# workflow triggers
on:
  # manually
  workflow_dispatch:
  workflow_call:
  # PRs on `main`
  pull_request:
    branches:
    - build/pure-maven

jobs:
  ci:
    name: Checkstyle
    runs-on: ubuntu-latest
    
    steps:
    # checkout repository
    - name: Checkout
      uses: actions/checkout@v4.1.1
    
    - name: setup review dog
      uses: reviewdog/action-setup@v1
      with:
        reviewdog_version:

    # setup Java and cache Maven dependencies
    - name: Setup Java
      uses: actions/setup-java@v3.13.0
      with:
        distribution: 'temurin'
        java-version: '17'
        check-latest: true
        cache: 'maven'

    # run Maven Checkstyle
    - name: Maven Checkstyle
      run: ./mvnw checkstyle:check
    
    - name: Run reviewdog
      #env:
        #REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: 
        ./mvnw checkstyle:check . | reviewdog -f=checkstyle -diff="git diff" -name=eslint" -reporter=github-Check