name: Static Code Review

# workflow triggers
on:
  # manually
  workflow_dispatch:
  workflow_call:
  # PRs on `main`
  pull_request:
    branches:
    - build/pure-maven

jobs:
  ci:
    name: CI on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
    # checkout repository
    - name: Checkout
      uses: actions/checkout@v4.1.1

    # setup Java and cache Maven dependencies
    - name: Setup Java
      uses: actions/setup-java@v3.13.0
      with:
        distribution: 'temurin'
        java-version: '17'
        check-latest: true
        cache: 'maven'

    # run Maven build
    - name: Maven Checkstyle
      run: ./mvnw checkstyle:check
