name: Validation

on:
  pull_request:

jobs:
  validate_change:
    name: Change
    uses: ./.github/workflows/ci.yml
          
  validate_framework:
    needs: validate_change
    name: Framework
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download Change Artifact
        uses: actions/download-artifact@v3
        with:
          name: change
          path: change
      - name: Checkout Framework
        uses: actions/checkout@v3
        with:
          path: framework
          repository: vitruv-tools/Vitruv
          ref: main
          fetch-depth: 0
      - name: Checkout Matching Framework Branch
        run: |
          cd framework
          git checkout -B ${{ github.head_ref }} origin/${{ github.head_ref }} || true
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/MANIFEST.MF') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build and Verify Framework
        working-directory: ./framework
        run: >
          ./mvnw -B -U clean verify
          '-Dvitruv.change.url=file:///${{ github.workspace }}/change'
          '-Dstyle.color=always'
          '-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'
          '-Dorg.slf4j.simpleLogger.log.org.eclipse.tycho.core.resolver.DefaultTychoResolver=warn'
          '-Dorg.slf4j.simpleLogger.log.org.eclipse.tycho.osgi.configuration.MavenContextConfigurator=warn'
          '-Dorg.slf4j.simpleLogger.log.org.eclipse.sisu.equinox.launching.internal.DefaultEquinoxLauncher=warn'
          '-Dorg.slf4j.simpleLogger.log.org.eclipse.xtext.maven.XtextGenerateMojo=warn'
          '-Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.NoOpLog'
        env: 
          MAVEN_OPTS: -Djansi.force=true
      - name: Store Framework Artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: framework
          path: framework/releng/tools.vitruv.updatesite/target/repository
          retention-days: 1

  validate_DSLs:
    needs: validate_change
    name: DSLs
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download Change Artifact
        uses: actions/download-artifact@v3
        with:
          name: change
          path: change
      - name: Checkout DSLs
        uses: actions/checkout@v3
        with:
          path: dsls
          repository: vitruv-tools/Vitruv-DSLs
          ref: main
          fetch-depth: 0
      - name: Checkout Matching DSLs Branch
        run: |
          cd dsls
          git checkout -B ${{ github.head_ref }} origin/${{ github.head_ref }} || true
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/MANIFEST.MF') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build and Verify DSLs
        uses: GabrielBB/xvfb-action@v1
        with:
          working-directory: ./dsls
          run: >
            ./mvnw -B -U clean verify
            -Dvitruv.change.url=file:///${{ github.workspace }}/change
            -Dstyle.color=always
            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
            -Dorg.slf4j.simpleLogger.log.org.eclipse.tycho.core.resolver.DefaultTychoResolver=warn
            -Dorg.slf4j.simpleLogger.log.org.eclipse.tycho.osgi.configuration.MavenContextConfigurator=warn
            -Dorg.slf4j.simpleLogger.log.org.eclipse.sisu.equinox.launching.internal.DefaultEquinoxLauncher=warn
            -Dorg.slf4j.simpleLogger.log.org.eclipse.xtext.maven.XtextGenerateMojo=warn
            -Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.NoOpLog
        env: 
          MAVEN_OPTS: -Djansi.force=true
      - name: Store DSLs Artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: dsls
          path: dsls/releng/tools.vitruv.dsls.updatesite/target/repository
          retention-days: 1

  validate_casestudies:
    needs: [validate_change, validate_framework, validate_DSLs]
    name: Case Studies
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download Change Artifact
        uses: actions/download-artifact@v3
        with:
          name: change
          path: change
      - name: Download Framework Artifact
        uses: actions/download-artifact@v3
        with:
          name: framework
          path: framework
      - name: Download DSLs Artifact
        uses: actions/download-artifact@v3
        with:
          name: dsls
          path: dsls
      - name: Checkout Case Studies
        uses: actions/checkout@v3
        with:
          path: casestudies
          repository: vitruv-tools/Vitruv-CaseStudies
          ref: main
          fetch-depth: 0
      - name: Checkout Matching Case Studies Branch
        run: |
          cd casestudies
          git checkout -B ${{ github.head_ref }} origin/${{ github.head_ref }} || true
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/MANIFEST.MF') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build and Verify Case Studies
        uses: GabrielBB/xvfb-action@v1
        with:
          working-directory: ./casestudies
          run: >
            ./mvnw -B -U clean verify
            -Dvitruv.change.url=file:///${{ github.workspace }}/change
            -Dvitruv.framework.url=file:///${{ github.workspace }}/framework
            -Dvitruv.dsls.url=file:///${{ github.workspace }}/dsls
            -Dstyle.color=always
            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
            -Dorg.slf4j.simpleLogger.log.org.eclipse.tycho.core.resolver.DefaultTychoResolver=warn
            -Dorg.slf4j.simpleLogger.log.org.eclipse.tycho.osgi.configuration.MavenContextConfigurator=warn
            -Dorg.slf4j.simpleLogger.log.org.eclipse.sisu.equinox.launching.internal.DefaultEquinoxLauncher=warn
            -Dorg.slf4j.simpleLogger.log.org.eclipse.xtext.maven.XtextGenerateMojo=warn
            -Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.NoOpLog
        env: 
          MAVEN_OPTS: -Djansi.force=true